### ISSUE TITLE
Fatal Error kills battle.

### ISSUE THREAD

**Issue by TheN1K0L4Z** [davo899/CobblemonTrainers#21]
Mixin apply failed mixins.cobblemontrainers-common.json:ShowdownInterpreterMixin -> com.cobblemon.mod.common.battles.ShowdownInterpreter: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on injectHandleSwitchInstruction could not find any targets matching 'handleSwitchInstruction' in com.cobblemon.mod.common.battles.ShowdownInterpreter. Using refmap cobblemontrainers-common-refmap.json [PREINJECT Applicator Phase -> mixins.cobblemontrainers-common.json:ShowdownInterpreterMixin -> Prepare Injections ->  -> handler$zic000$injectHandleSwitchInstruction(Lcom/cobblemon/mod/common/api/battles/model/PokemonBattle;Lcom/cobblemon/mod/common/api/battles/model/actor/BattleActor;Lcom/cobblemon/mod/common/api/battles/interpreter/BattleMessage;Lcom/cobblemon/mod/common/api/battles/interpreter/BattleMessage;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on injectHandleSwitchInstruction could not find any targets matching 'handleSwitchInstruction' in com.cobblemon.mod.common.battles.ShowdownInterpreter. Using refmap cobblemontrainers-common-refmap.json [PREINJECT Applicator Phase -> mixins.cobblemontrainers-common.json:ShowdownInterpreterMixin -> Prepare Injections ->  -> handler$zic000$injectHandleSwitchInstruction(Lcom/cobblemon/mod/common/api/battles/model/PokemonBattle;Lcom/cobblemon/mod/common/api/battles/model/actor/BattleActor;Lcom/cobblemon/mod/common/api/battles/interpreter/BattleMessage;Lcom/cobblemon/mod/common/api/battles/interpreter/BattleMessage;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46)
	at jdk.internal.reflect.GeneratedConstructorAccessor59.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1311)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1042)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.cobblemon.mod.common.battles.runner.graal.GraalShowdownService.sendFromShowdown(GraalShowdownService.java:188)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.host.HostMethodDesc$SingleMethod$MHBase.invokeHandle(HostMethodDesc.java:350)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.host.GuestToHostCodeCache$1.executeImpl(GuestToHostCodeCache.java:96)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.host.GuestToHostRootNode.execute(GuestToHostRootNode.java:80)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:85)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.api.impl.DefaultRuntimeAccessor$DefaultRuntimeSupport.callInlined(DefaultRuntimeAccessor.java:177)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.host.GuestToHostRootNode.guestToHostCall(GuestToHostRootNode.java:102)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.host.HostMethodDesc$SingleMethod$MHBase.invokeGuestToHost(HostMethodDesc.java:386)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.host.HostExecuteNode.doInvoke(HostExecuteNode.java:871)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.host.HostExecuteNode.doFixed(HostExecuteNode.java:137)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.host.HostExecuteNodeGen.executeAndSpecialize(HostExecuteNodeGen.java:144)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.host.HostExecuteNodeGen.execute(HostExecuteNodeGen.java:97)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.host.HostObject.invokeMember(HostObject.java:454)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.host.HostObjectGen$InteropLibraryExports$Cached.invokeMemberNode_AndSpecialize(HostObjectGen.java:2696)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.host.HostObjectGen$InteropLibraryExports$Cached.invokeMember(HostObjectGen.java:2678)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.invokeMember(InteropLibraryGen.java:8328)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.js.nodes.function.JSFunctionCallNode$ForeignInvokeNode.executeCall(JSFunctionCallNode.java:1534)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeAndSpecialize(JSFunctionCallNode.java:306)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeCall(JSFunctionCallNode.java:251)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.js.nodes.function.JSFunctionCallNode$InvokeNode.execute(JSFunctionCallNode.java:740)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.js.nodes.JavaScriptNode.executeVoid(JavaScriptNode.java:192)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:80)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:55)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.api.impl.DefaultBlockNode.executeVoid(DefaultBlockNode.java:73)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:70)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.js.nodes.control.AbstractRepeatingNode.executeBody(AbstractRepeatingNode.java:67)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.js.nodes.control.WhileNode$WhileDoRepeatingNode.resume(WhileNode.java:249)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.js.nodes.control.GeneratorWrapperNode.execute(GeneratorWrapperNode.java:94)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.js.nodes.control.GeneratorWrapperNode.executeRepeating(GeneratorWrapperNode.java:104)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.api.nodes.RepeatingNode.executeRepeatingWithValue(RepeatingNode.java:112)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.api.impl.DefaultLoopNode.execute(DefaultLoopNode.java:64)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.js.nodes.control.WhileNode.execute(WhileNode.java:175)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.js.nodes.control.AsyncIteratorCloseWrapperNode.executeBegin(AsyncIteratorCloseWrapperNode.java:99)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.js.nodes.control.AsyncIteratorCloseWrapperNode.execute(AsyncIteratorCloseWrapperNode.java:154)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.js.nodes.control.TryFinallyNode.resume(TryFinallyNode.java:129)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.js.nodes.control.GeneratorWrapperNode.execute(GeneratorWrapperNode.java:94)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.js.nodes.JavaScriptNode.executeVoid(JavaScriptNode.java:192)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.js.nodes.control.AbstractGeneratorBlockNode.executeVoid(AbstractGeneratorBlockNode.java:90)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.js.nodes.control.AbstractGeneratorBlockNode.executeVoid(AbstractGeneratorBlockNode.java:47)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.api.impl.DefaultBlockNode.executeVoid(DefaultBlockNode.java:73)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.js.nodes.control.AbstractGeneratorBlockNode.executeVoid(AbstractGeneratorBlockNode.java:74)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.js.nodes.control.GeneratorVoidBlockNode.execute(GeneratorVoidBlockNode.java:61)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.js.nodes.function.BlockScopeNode$VirtualBlockScopeNode.resume(BlockScopeNode.java:344)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.js.nodes.control.GeneratorWrapperNode.execute(GeneratorWrapperNode.java:94)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.js.nodes.function.FunctionBodyNode.execute(FunctionBodyNode.java:73)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.js.nodes.control.AsyncFunctionBodyNode$AsyncFunctionRootNode.executeInRealm(AsyncFunctionBodyNode.java:138)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:88)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:85)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.api.impl.DefaultDirectCallNode.call(DefaultDirectCallNode.java:59)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.js.nodes.function.InternalCallNode.directCall(InternalCallNode.java:70)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.js.nodes.function.InternalCallNodeGen.executeAndSpecialize(InternalCallNodeGen.java:83)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.js.nodes.function.InternalCallNodeGen.execute(InternalCallNodeGen.java:49)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.js.nodes.control.AwaitResumeNode.execute(AwaitResumeNode.java:69)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.js.nodes.control.AbstractAwaitNode$AwaitSettledRootNode.execute(AbstractAwaitNode.java:293)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:85)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.api.impl.DefaultDirectCallNode.call(DefaultDirectCallNode.java:59)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.js.nodes.function.JSFunctionCallNode$UnboundJSFunctionCacheNode.executeCall(JSFunctionCallNode.java:1314)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeAndSpecialize(JSFunctionCallNode.java:306)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeCall(JSFunctionCallNode.java:251)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.js.nodes.promise.PromiseReactionJobNode$PromiseReactionJobRootNode.execute(PromiseReactionJobNode.java:145)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:85)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.api.impl.DefaultCallTarget.call(DefaultCallTarget.java:102)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.js.runtime.builtins.JSFunction.call(JSFunction.java:314)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.js.runtime.JSAgent.processAllPromises(JSAgent.java:150)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.js.lang.JavaScriptLanguage.interopBoundaryExit(JavaScriptLanguage.java:520)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.js.runtime.interop.InteropBoundFunction.execute(InteropBoundFunction.java:114)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.js.runtime.interop.InteropBoundFunctionGen$InteropLibraryExports$Cached.execute(InteropBoundFunctionGen.java:168)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.api.interop.InteropLibraryGen$Delegate.execute(InteropLibraryGen.java:3886)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.execute(InteropLibraryGen.java:7765)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue$AbstractExecuteNode.executeShared(PolyglotValueDispatch.java:4268)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue$ExecuteNode.executeImpl(PolyglotValueDispatch.java:4349)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.polyglot.HostToGuestRootNode.execute(HostToGuestRootNode.java:124)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:85)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.api.impl.DefaultCallTarget.call(DefaultCallTarget.java:102)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.api.impl.DefaultRuntimeAccessor$DefaultRuntimeSupport.callProfiled(DefaultRuntimeAccessor.java:182)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue.execute(PolyglotValueDispatch.java:2396)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/org.graalvm.polyglot.Value.execute(Value.java:880)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.cobblemon.mod.common.battles.runner.graal.GraalShowdownService.startBattle(GraalShowdownService.java:130)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.cobblemon.mod.common.battles.BattleRegistry.startShowdown(BattleRegistry.java:199)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.cobblemon.mod.common.battles.BattleRegistry.startBattle(BattleRegistry.java:214)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.cobblemon.mod.common.battles.BattleRegistry.startBattle$default(BattleRegistry.java:202)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.cobblemon.mod.common.battles.BattleBuilder.pve(BattleBuilder.java:132)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.cobblemon.mod.common.battles.BattleBuilder.pve$default(BattleBuilder.java:92)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.cobblemon.mod.common.net.serverhandling.ChallengeHandler.handle(ChallengeHandler.java:53)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.cobblemon.mod.common.net.serverhandling.ChallengeHandler.handle(ChallengeHandler.java:29)
	at TRANSFORMER/cobblemon@1.5.2+1.20.1/com.cobblemon.mod.common.api.net.ServerNetworkPacketHandler$DefaultImpls.handleOnNettyThread$lambda$0(ServerNetworkPacketHandler.java:19)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.TickTask.run(TickTask.java:18)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:770)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:753)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:733)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by TheN1K0L4Z** [comment]
So, apparently, Something is conflicting the Injection with the latest modpack release I'm using, and your latest mod version I'm using for forge. Could this be further indication that, you need to modify the mod again?
